# Generated by Django 3.0.3 on 2020-03-01 18:37

from django.db import migrations


def transfer_companies(apps, schema_editor):
    User = apps.get_model('core', 'User')

    for user in User.objects.all():
        if user.company_id:
            user.companies.add(user.company)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200301_2135'),
    ]

    operations = [
        migrations.RunPython(transfer_companies),
    ]
