# Generated by Django 3.0.3 on 2020-04-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Администратор'),
        ),
    ]
