# Generated by Django 3.0.3 on 2020-04-10 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_company_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTimeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('work_date', models.DateField(null=True, verbose_name='Дата работы')),
                ('work_hours', models.FloatField(verbose_name='Потрачено рабочих часов')),
                ('minus_work_time', models.BooleanField(default=False, verbose_name='Сминусовать отработанное время')),
                ('text', models.TextField(default='')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_time_history', to='core.Task', verbose_name='Задача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись о списании времени',
                'verbose_name_plural': 'Записи о списании времени',
            },
        ),
    ]
